# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# env:
#   ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/x.x.x
#   ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/x.x.x

jobs:
  build-android:

    runs-on: ubuntu-latest

#     env:
#       ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/x.x.x
#       ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/x.x.x

    steps:

    - uses: actions/checkout@v3

#     JDK

    - name: Set up JDK 18
      uses: actions/setup-java@v3.1.1
      with:
        java-version: 18
        distribution: temurin

#     NDK (Standalone toolchains obsolete)

    - name: Set up NDK 25 Beta 2
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r25-beta2 # Ubuntu 20.04: r21e, r22, r23b, Custom: r24+

    # - name: Set NDK r24 env vars
      # run: |
        # export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk/x.x.x
        # export ANDROID_NDK_ROOT=/usr/local/lib/android/sdk/ndk/x.x.x

    - name: Install with Yarn # 5s cached
      run: yarn

#     - name: Clean with Gradle # 40m, same repeated, ~75% less 1 ABI
#       run: cd android && ./gradlew clean

#     - name: Build project Make-based (not CMake)
#       run: |
#         /usr/local/lib/android/sdk/ndk/24.0.8215888/ndk-build
#         NDK_PROJECT_PATH=null
#         APP_BUILD_SCRIPT=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/react/jni/Android.mk
#         NDK_APPLICATION_MK=/home/runner/work/react-native-template-new-architecture/react-native-template-new-architecture/node_modules/react-native/ReactAndroid/src/main/jni/Application.mk

#     - name: Build Release with Gradle
#       run: cd android && chmod +x gradlew && ./gradlew <task>

    - name: Build Debug with Gradle
      uses: gradle/gradle-build-action@v2.1.5
      with:
        arguments: assembleDebug
        build-root-directory: android

    - name: Build Release with Gradle
      uses: gradle/gradle-build-action@v2.1.5
      with:
        arguments: assembleRelease
        build-root-directory: android
