name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows run workflow from Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DAY_OF_WEEK: Mon

    steps:
      - uses: actions/checkout@v2
      
      - name: "Hello world when it's Monday"
        if: ${{ env.DAY_OF_WEEK == 'Mon' }}
        run: echo "Hello $FIRST_NAME $middle_name $Last_Name, today is $DAY_OF_WEEK!"
        env:
          FIRST_NAME: Mona
          middle_name: The
          Last_Name: Octocat

      - name: Install with Yarn
        run: yarn

      - name: Compile with TypeScript
        run: yarn tsc

      - name: Lint with ESLint
        run: yarn lint

      - name: Test with Jest
        run: yarn test
